### ISSUE TITLE
how to download datasets?

### ISSUE THREAD

**Issue by Lukangkang123** [christinecui/LAGNH#1]
Thanks for you providing the code. But I want to know how to download datasets you used as follows:
![sendpix0](https://user-images.githubusercontent.com/38984189/138701273-a06edba0-60be-4dc2-a37d-d9e2131b839b.jpg)

**Comment by govvc** [comment]
Have you got the dataset? It would be much appreciated if you could share the dataset, Thanks a lot.

**Comment by christinecui** [comment]
Sorry to reply later.
You can download the datasets via https://pan.baidu.com/s/1LoRHV5P0YdpJszUlrdXCMg 
提取码：9mel

**Comment by govvc** [comment]
Thanks a lot, wish you a good day sir.
