### ISSUE TITLE
Issue about the missing file ARGA

### ISSUE THREAD

**Issue by govvc** [christinecui/LAGNH#2]
After read your paper, I'm very interested in how you implement the mothed you proposed, but the code you post seems like miss the ARGA.layers python file, could you please check it twice and post that .py file? It would help me a lot, thanks.
![](https://gitee.com/govvc/images/raw/master/QQ%E6%88%AA%E5%9B%BE20211125143336.png)

**Comment by christinecui** [comment]
Sorry for missing this file.
It has been uploaded. 
Thanks for your reminding .

**Comment by govvc** [comment]
Thanks for your help:)
