### ISSUE TITLE
您好，请问可以提供一下数据集中的pkl文件吗

### ISSUE THREAD

**Issue by Junyanzhang** [christinecui/LAGNH#3]
## COCO-data
paths_COCO = {
    'COCO_train': '/Data/data/COCO/pkl/train2017.pkl',
    'COCO_val': '/Data/data/COCO/pkl/val2017.pkl',
    'COCO_retrieval': '/Data/data/COCO/pkl/retrieval2017.pkl',
}
## NUSWIDE
paths_NUSWIDE = {
    'NUSWIDE_train': '/Data/data/NUSWIDE/pkl/train.pkl',
    'NUSWIDE_val': '/Data/data/NUSWIDE/pkl/val.pkl',
    'NUSWIDE_retrieval': '/Data/data/NUSWIDE/pkl/retrieval.pkl'
}

**Comment by christinecui** [comment]
你好，请参考the closed issues #1

**Comment by Junyanzhang** [comment]
> 你好，请参考the closed issues #1

感谢您及时的回复，我想问一下怎么去生成这些pkl文件，有相关参考的代码吗

**Comment by christinecui** [comment]
你好，pkl文件中的特征部分采用SADH (TPAMI 2018)所提供的特征抽取代码 ([fc7_features](https://github.com/xuyan1115/Similarity-Adaptive-Deep-Hashing/tree/master/fc7_features))：


tag部分使用pytorh中自带的fasterrcnn模型进行提取
label部分来自原始数据集
